<a href="https://colab.research.google.com/github/Dylan-32/unidad1/blob/main/Actividad6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dylan omar pedroza - 24 de septiembre de 2025 practica-6 cortar arreglos numpy
-----------------------------------------------------------------------------
slice en python  significa tomar elementos de un indice determinado ah otro determinado indice.

pasamos slice en lugar de indice de esta manera: [start:end]
si no pasamos este inicio se considera 0
si no pasamos  el final su longuitud es considerada una matrizde una dimension
--------------------
ejemplo: ([1,2,3,4,5,6,7])
cortar los elementos del indice 1 al indice 5                                                              


In [1]:
import numpy as np

arreglo = np.array([1,2,3,4,5,6,7])

print(arreglo[1:5])

[2 3 4 5]


Elmplo 2:([1,2,3,4,5,6,7]) cortar el indice 4 hasta el final dela matriz

In [2]:
import numpy as np

arreglo = np.array ([1,2,3,4,5,6,7])

print(arreglo [4:])

[5 6 7]


Ejenmplo 3:([1,2,3,4,5,6,7,]) cortar elemntos desde el principio asta al indice 5

In [3]:
import numpy as np

arreglo = np.array([1,2,3,4,5,6,7])

print(arreglo[:5])

[1 2 3 4 5]


Elemplo 4 ([1,2,3,4,5,6,7]) corte negativo.utilizarnos el operador "menos" para hacer referencia a un indice desde el final.
-------------------------------------------
cortar el indice 3 desde el final del indice

In [4]:
import numpy as np

arreglo = np.array([1,2,3,4,5,6,7])

print(arreglo[-3: -1])

[5 6]
