<a href="https://colab.research.google.com/github/Dylan-32/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy es una libreria de python.
Numpy se utiliza para trabajar  con matrices o arreglo
Numpy es la abreviatura de "python  numerioco"
Tambien tiene funciones para trabajar en el dominio del algebra lineal,la transformada y las matrices
En python tenemos listas que sirven como matrices pero ,son lentas de procesar
Numpy tiene como objetivo  proporcionar un objeto de matriz que sea 50 veces mas rapido que las lineas tradicionales.

In [1]:
#primero tenemos que importar la libreria
import numpy

arreglo = numpy.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


Numpy como np
Numpy generalmente  se importa  bajo el alias np.
En python los alias son un nombre  alternativo para referirse  ala misma cosa

In [2]:
import numpy as np

arreglo = np.array([6,7,8,9,10])
print(arreglo)

[ 6  7  8  9 10]


comprobando la version de numpy
la cadena de la version se almacena en el atributo__version__

In [3]:
import numpy as np

print(np.__version__)

2.0.2


Numpy creando matrices
crear un objeto ndarray de Numpy se utiliza para trabajar con matrices .El objeto de matriz se llama ndrray .
podemos crear un numpy ndarray utilizando la funcion array()

In [5]:
import  numpy as np
arreglo = np.array(["dylan","danna"])
print(arreglo)
print(type(arreglo))

['dylan' 'danna']
<class 'numpy.ndarray'>


dimenciones en matrices un dimension en matrices es un nivel de profundidad de matriz(matrices unidades)
una matriz unidada contiene matrices como elementos
matrices0-D. son elementos de una matriz.Cada valor de una matriz es una matriz0-D. Ejemplo:crea una matriz 0-D con valor de 42


In [20]:
import numpy as np

arreglo = np.array(42)

print(arreglo)

42


matrices 1-D  una matriz que tiene matrices 0-D como element5o se denomina matriz unidimesional  o 1-D estas son las matrices mas comunes o basicas  Ejemplo: matriz de 1-D los valores 1,2,3,4,5

In [21]:
import numpy as np

arreglo = np.array([1,2,3,4,5])

print(arreglo)

[1 2 3 4 5]


matrices 2D
uma matriz que tiene matrices 1-D como elemento  se denomina matriz 2-D.
A menudo se utilizan para presentar matrices de segundo orden . Numpy tiene un submodulo  completo dedicado a operaciones con matrices  llamado numpy.mat.
Ejemplo:crea un matriz 2D que con tenga dos matrices con los valores 123 y 459.

In [22]:
import numpy as np

arreglo = np.array([[1,2,3],[4,5,6]])

print(arreglo)

[[1 2 3]
 [4 5 6]]


Matrices 3D
una matriz que tiene matrices 2d se denomina matriz 3D.
estas matrices se utilizan para representar una matriz de tercer orden.
Ejemplo:crea una matriz 3D con dos matrices bidimensionales,conteniendo dos matrices con los valores 1,2,3 y 4,5,6

In [25]:
import  numpy as np

arreglo = np.array ([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print (arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
