<a href="https://colab.research.google.com/github/Dylan-32/unidad1/blob/main/practica7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dylan  Omar Pedroza -practica 7-25 de septiembre de 2025
---------------------------------------
slicing numpy
----------------
utilice step para determinar el paso del corte:
Ejemplo: ([1,2,3,4,5,6,7])- devuelve todos los elementos del indice 1 al 5

In [1]:
import numpy as np

arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[1:5:2])

[2 4]


Ejemplo 2: (1,2,3,4,5,6,7) devuelve los elemtos dela matriz

In [2]:
import numpy as np
arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[::2])


[1 3 5 7]


slice de matrices 2D
------------------------
Ejemplo3: ([[1,2,3,4,5]),[6,7,8,9,10]])
del segundo elemento, corte del indice 1 al indice 4


In [5]:
import numpy as np
arreglo = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[1, 1:4])

[7 8 9]


ejemplo 4: ([[1,2,3,4,,5],[6,7,8,9,10]])
de ambos elementos,devuelve el indice 2

In [8]:
import numpy as np
arreglo = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


Ejemplo 5:([[1,2,3,4,5],[6,7,8,9,10]]) de ambos elementos corta el inidice del 1 al 4

In [7]:
import numpy as np
arreglo  = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arreglo[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


ejercicio 1 - Autonomo
del siguiente arreglo, ¿cual es el resultado?
([1,2,3,4,5,6,7])
corta del 1er elemnto al 6to elemento con 2 pasos

In [12]:
import numpy as np
arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[0:6:2])

[1 3 5]
